### ISSUE TITLE
More options for establishing local DNS authority

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-add/draft-ietf-add-split-horizon-authority#10]
Currently, the draft requires DNR or IKEv2 ADN support. This is great when you have it, but many enterprise networks will be much harder to upgrade.

If we can support other mechanisms that don't require router changes as a stopgap, that would be great. For example, something based on the names in the cert we get for DDR.

**Comment by tfpauly** [comment]
One other interesting option is associating information from the network authentication, like an EAP-TLS network.

**Comment by danwing** [comment]
On Jul 26, 2022, at 12:34 PM, Tommy Pauly ***@***.***> wrote:
> Currently, the draft requires DNR or IKEv2 ADN support. This is great when you have it, but many enterprise networks will be much harder to upgrade.
> 
> If we can support other mechanisms that don't require router changes as a stopgap, that would be great. For example, something based on the names in the cert we get for DDR.

See if https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/pull/11 feels about right.

-d

**Comment by tireddy2** [comment]
Issue resolved in 01 version.

**Comment by danwing** [comment]
On Jul 27, 2022, at 3:27 PM, Tommy Pauly ***@***.***> wrote:
> One other interesting option is associating information from the network authentication, like an EAP-TLS network.

Yes, Paul Wouters brought up a similar idea in his Discuss on DNR, https://datatracker.ietf.org/doc/draft-ietf-add-dnr/ballot/,

> Spoofing attacks are mentioned in the document. Obtain _any_ certificate 
> from Let's Encrypt via ACME, eg using "something.example.com", then spoof 
> authentication-domain-name on the wifi. While this attack might be blocked 
> by the AP not allowing wifi clients to send packets to each other, this is 
> not true for all networks, and especially not for home networks where the 
> goal is for local clients to be able to connect to each other.  Is there a 
> better way to lock the authentication-domain-name? One possible method 
> might be to bind it to the ESSID. eg if the ESSID is wifi.nohats.ca. one 
> could only allow authentication-domain-name to be a name within nohats.ca. 
> Some method of reducing the scope of this attack is needed I believe.


Doing something useful with EAP-TLS or ESSID seems fruitful.  Taking Paul's ESSID idea for example, the ESSID doesn't have to necessarily be the DNS name but instead there could be a mapping from "Starbucks" to the certificate expected at that ESSID (which for Starbucks networks managed by AT&T would not be starbucks.com).  I have been disappointed with IEEE's approach to WiFi security and it feels like a TLS connection to something -- like the network-advertised encrypted DNS server -- can close evil-twin attacks and perhaps close other attacks as well.

I don't think split-horizon is the place to do it, though.  And it feels like scope creep to include into DNR or DDR, as well, as their primary goal is "quit using DNSo53 on local network", rather than "fix WiFi evil twin attacks".  Perhaps a new I-D in the SEC area, "Enhancing WiFi Security with TLS to Network-Advertised Server", could be a reasonable start.  That application server could be DoH/DoT like we're thinking, but I suppose could also be HTTPS or Network Time Security (RFC8915) as NTP is typically advertised for the local network (much like DNSo53).

-d
