### ISSUE TITLE
Make it easier for local resolvers to sign their zones without holding the public zone's private keys

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-add/draft-ietf-add-split-horizon-authority#18]
In the current draft, it is possible to have a fully signed zone without giving the local resolver the public zone's private keys, in certain configurations.  For example, consider the following arrangement:

~~~zone
; Public Zone
$ORIGIN example.com.

@ IN NS ns.example.com.
ns IN A 3600 192.0.2.2

@ IN DNSKEY 256 3 13 123...
@ IN DNSKEY 257 3 13 ABC...

www IN A 3600 192.0.2.1

; Delegation Glue records
internal IN NS ns-internal
ns-internal IN A 192.0.2.3

internal IN DS ...
~~~
~~~zone
; Public view of ns-internal.example.com
$ORIGIN internal.example.com.

@ IN NS ns-internal.example.com.

@ IN DNSKEY 256 3 13 456...
@ IN DNSKEY 257 3 13 DEF...
~~~
~~~zone
; Internal zone for resolver claiming ns-internal.example.com.
$ORIGIN internal.example.com.

@ IN NS ns-internal.example.com.

@ IN DNSKEY 256 3 13 456...
@ IN DNSKEY 257 3 13 DEF...

secret-label IN A 10.0.0.123 ;; This label is only visible internally.
~~~

However, this arrangement requires a live, public-facing nameserver for the internal zone, with the same keys as the internal nameserver.  This may be operationally inconvenient in some situations.  It's also not compatible with the prefix-driven approach that some ADD members have been asking for.

**Comment by paulwouters** [comment]
The problem here is:

`internal IN NS ns-internal
ns-internal IN A 192.0.2.3`

These NS and A records are glue records, so it won't get signed by DNSSEC, so it cannot be trusted (transport layer security is not data authenticity). So the client pulling this record (eg indirectly via some public DoH server or even if it is iterating/validating itself) cannot trust these records.

If you did a DS record, then it would get signed as that is not glue. And using a proper prefix, it could authenticate the name of the internal only zone. When using the DS record, the actual IP of the nameserver or its internal name is irrelevant and does not need to by synchronized.

**Comment by bemasc** [comment]
No, the DoH resolver will fetch `@ IN NS ns-internal.example.com.` from 192.0.2.3 and validate RRSIGs.

This example _does_ have a DS record, in the public zone (`internal IN DS ...`).  Notably, in this example both versions of ns-internal.example.com have the same DNSKEYs, in order to share that DS record.  (Perhaps I should change the example to have two DS records instead...)

I've added a comment highlighting the glue records.

**Comment by bemasc** [comment]
I've described a possible approach to this as part of #19 (specifically [here](https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/pull/19/files#diff-88327ee1fab3b36a3051ae5a5d5df751b77b1481cde9b4cb29510def1a6dc0b1R364-R384)).
